import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;

/*
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 */


public class problem29
{
    private ArrayList<Long> list;
    private BigInteger bd;
    private int count;

    public void distinctPowers(int a , int b)
    {
        list = new ArrayList<Long>();
        count = 0;
        //bd = new BigInteger("987654321987654321987654321987");

        for (int i = 2; i <= a ; i++)
        {
            for (int j = 2; j <= b ; j++)
            {
                long c = (long) Math.pow(i,j);
                //System.out.println(c);
                list.add(c);
                count++;
            }
        }
    }

    public void sort()
    {
        Collections.sort(list);

        for (Long counter : list)
        {
            System.out.println(counter);
        }
        System.out.println(count);
    }

    public static void main(String[] args) {
        problem29 p = new problem29();

        p.distinctPowers(10,10);
        p.sort();


    }
}
